# Generated by Django 3.2.10 on 2021-12-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField()),
                ('name', models.CharField(max_length=250)),
                ('client_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=5)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
