# Generated by Django 3.2.10 on 2021-12-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20211215_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressofproject',
            name='drawing',
        ),
    ]
