# Generated by Django 3.2.10 on 2021-12-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_remove_progressofproject_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressofproject',
            name='is_removed',
        ),
        migrations.AlterField(
            model_name='project',
            name='is_removed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_removed',
            field=models.BooleanField(),
        ),
    ]
