# Generated by Django 3.2.10 on 2021-12-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20211215_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressofproject',
            name='drawing',
            field=models.CharField(default='test01-100', max_length=100),
            preserve_default=False,
        ),
    ]
