# Generated by Django 3.2.10 on 2022-01-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_progressofproject_drawing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='User',
        ),
    ]
