# Generated by Django 3.2.10 on 2022-01-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0009_auto_20220116_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_removed',
        ),
    ]
