# Generated by Django 3.2.10 on 2022-01-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_remove_user_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], default='Level 1', max_length=10),
            preserve_default=False,
        ),
    ]
