# Generated by Django 3.2.10 on 2022-01-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_alter_project_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressofproject',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to=''),
        ),
    ]
