# Generated by Django 3.2.10 on 2022-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_progressofproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressofproject',
            name='is_removed',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progressofproject',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
