# Generated by Django 3.2.10 on 2022-01-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0015_auto_20220122_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
