# Generated by Django 3.2.10 on 2022-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_alter_progressofproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressofproject',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
