# Generated by Django 3.2.10 on 2022-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0021_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressofproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
