# Generated by Django 3.2.10 on 2022-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0023_auto_20220719_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_live',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('done', 'Done!')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
